created pull request template file
atlp-rwanda/e-comm-team-techsmith-bn pull request #14
Opened 2023-03-29 06:45 UTC by cyubahiro367

2023-03-29 08:50 UTC, jcharles921 submitted a review, later dismissed

2023-03-29 08:54 UTC, jcharles921 reviewed
won't you use it in your Pull request ? 😅 , i mean that template

2023-03-30 06:04 UTC, jcharles921 requested changes
You should edit your PR using the template you Provided , also request more reviewers

2023-03-30 14:24 UTC, nishimweprince requested changes
Following are my suggestions:
- Consider using two hashtags `(##)` instead if of four (####) to make the heading bigger.
- Indicate that the Story_ID and Story description are the PR title to avoid confusions.

2023-04-03 12:18 UTC, closed without merging