ft-reset-password
atlp-rwanda/e-comm-team-techsmith-bn pull request #22
Opened 2023-03-31 08:06 UTC by Tparfaite

# What does this PR do 
implements the functionality for resetting password
# description of the task to be completed
. Create a reset password route and controller function that generates a unique token and sends a password reset email to the user's registered email address.
. Create a route and controller function for resetting the password using the token sent to the user's email address.
.Add necessary validation checks to ensure the token is valid and not expired before allowing the password reset.
.Update the user's password in the database and log them in automatically after the password reset is successful.
# How should this be manually tested
. Clone this repository
. cd into it
. Run `npm install`
. Add .env file
. Run `npm run migrate` to add all migrations
. Run `npm run seed`
. Start the server by `npm run dev`
. In post man send post request `localhost://{PORT}/api/user/requestReset` to request reset token
. Make a post request also `localhost://{PORT}/api/user/resetpassword/{token}` to reset your password
# relevant pivotal tracker user story
#184752092

2023-04-03 07:22 UTC, irakevine approved these changes

2023-04-04 09:08 UTC, niyontwali requested changes
Could you please rebase your branch to develop. Your branch has a lot of conflicts with the base branch. 
Also remember to squash your commits to only one.

2023-04-04 20:39 UTC, frankflej approved these changes
great

2023-04-04 20:41 UTC, jcharles921 approved these changes
Great work Parfaite 🔥✨✨✨

2023-04-05 06:32 UTC, niyontwali commented
Hello @Tparfaite some of the checks failed, please make sure your tests are done and complete

2023-04-05 06:36 UTC, nshutijonathan reviewed
Rename your commit message and always try to squash them into one or two

2023-04-05 06:36 UTC, nshutijonathan commented on src/test/passwordReset.test.js
> +  const resetToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBhcmZhaXRldHdhZ2lyYUBnbWFpbC5jb20iLCJpYXQiOjE2ODA0NDYxMjcsImV4cCI6MTY4MDQ0OTcyN30.T7XsdFEI0ft0xW6MFFPvWjF3mkvihgB6RToIoGD5Ryk'
load the token from `.env`

2023-04-05 19:02 UTC, niyontwali approved these changes
Well done

2023-04-05 20:10 UTC, merged