#184752097 Updating user password
atlp-rwanda/e-comm-team-techsmith-bn pull request #31
Opened 2023-04-03 16:01 UTC by frankflej

## What does this PR do?
It helps a user update a password
## Description of Task to be completed?
If the user might want to change the password in case they want to this PR helps them in changing their password

## How should this be manually tested?

- Clone the repository using git clone [link](https://github.com/atlp-rwanda/e-comm-team-techsmith-bn)

- Install node packages that the application depends on: `npm install`

- Create a .env file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.

- Start the application development server: `npm run dev`

- Test the user registration endpoint available on this address: `https://localhost:{PORT}/api/user/updPassword`, PORT being a local port that the application is running on.

- You can use Postman in your test by provinding the `oldPassword`, `newPassword` and `confPassword` in the body

- If `oldPassword` matches the password in the database and the passwords provided are the same then its a successfull update.

## What are the relevant pivotal tracker/Trello stories?
#184752097

2023-04-05 06:58 UTC, nshutijonathan requested changes
rebase properly

2023-04-05 06:58 UTC, nshutijonathan commented on .env.example
> +<<<<<<< HEAD
you have pushed conflicting files `<<<<<<< HEAD`

2023-04-05 06:58 UTC, nshutijonathan commented on .env.example
> +>>>>>>>                                                                           feature(Updating): Updating password
rebase properly `>>>>>>>`

2023-04-05 06:58 UTC, nshutijonathan commented on database/migrations/20230331113025-create-users.js
> +<<<<<<< HEAD:database/migrations/20230330000017-create-user.js
Incomplete rebase

2023-04-06 10:48 UTC, mken1205 approved these changes

2023-04-06 10:49 UTC, bergad37 approved these changes

2023-04-06 11:24 UTC, nishimweprince approved these changes
Great work also removing the .nyc_output folder into the files that Git is tracking.

2023-04-06 12:30 UTC, nshutijonathan approved these changes
LGTM

2023-04-06 13:02 UTC, merged