#184752088 Logout Functionality
atlp-rwanda/e-comm-team-techsmith-bn pull request #40
Opened 2023-04-07 12:19 UTC by irakevine

## What does this PR do?
Users should be able to log out of the application

## Description of Task to be completed?
When a user clicks on the logout link, they should be signed out of the application with their session ended.

## How should this be manually tested?
- Clone the repository using `git clone` [link](https://github.com/atlp-rwanda/e-comm-team-techsmith-bn)
- Install node packages that the application depends on: `npm install`
- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.
- Start the application development server: `npm run dev`
- Test the user registration endpoint available on this address: https:`//localhost:{PORT}/api/user/logout`, PORT being a local port that the application is running on.

## What are the relevant pivotal tracker/Trello stories?

- [#184752088](https://www.pivotaltracker.com/story/show/184752088)

2023-04-09 13:25 UTC, nishimweprince requested changes
Rebase with develop to remove conflicts and ensure you have the latest updates.

2023-04-09 17:34 UTC, jcharles921 approved these changes

2023-04-09 17:36 UTC, frankflej approved these changes

2023-04-09 17:49 UTC, bergad37 approved these changes

2023-04-10 08:25 UTC, niyontwali commented
Please rebase

2023-04-10 14:50 UTC, nishimweprince approved these changes

2023-04-10 16:13 UTC, niyontwali approved these changes

2023-04-10 16:13 UTC, merged