changing user's roles
atlp-rwanda/e-comm-team-techsmith-bn pull request #47
Opened 2023-04-11 20:34 UTC by ReneNtabana

## What does this P.R. do?
It gives the admin permission to manage other users.
## Description of Task to be completed?
Admin should be able to assign various users to various roles. There should also be a role for the admin account itself. This will allow only accounts with particular roles permission to perform particular actions.
## How should this be manually tested?
-Clone the repo and checkout to ft-authorisation-184752096 by typing `git checkout ft-authorization-184752096`
-Install the packages by running `npm install`
-Create a .env file in the root directory and add all environment variables required to run the application. The required variables are listed in the .env.example file available in the root directory of the application.  
-Start the application development server: `npm run dev`
## What are the relevant pivotal tracker/Trello stories?
#184752096

2023-04-11 22:00 UTC, nishimweprince requested changes
Your coveralls have dropped below the required threshold of **75%**. Please add more tests to make sure that the endpoints work as expected.

2023-04-12 15:39 UTC, nishimweprince approved these changes

2023-04-12 15:40 UTC, niyontwali approved these changes

2023-04-12 15:43 UTC, bergad37 approved these changes

2023-04-12 15:43 UTC, merged