ft-user-can-view-specific-item-184752101
atlp-rwanda/e-comm-team-techsmith-bn pull request #53
Opened 2023-04-16 18:26 UTC by Tparfaite

## What does this PR do?
- A User should be able to view a specific item

## Description of Task to be completed?
- A user as a buyer should be able to view specific item
- A user as a Seller I should be able to see an item if it is from my
collection.
-A user as a buyer I should be able to see any item from the available items.

## How should this be manually tested?
- First clone the repository
- Navigate to the branch by  running: **git checkout ft-user-can-view-specific-item-184752101**
- Use **npm install** to install the required dependencies.
- Use **npm run dev** to start the server
- Signup as a seller and add the products 
- Retrieve products you've created
- Signup as a buyer and retrieve all the available products or retrieve specific product using endpoints in documentation

## What are the relevant pivotal tracker/Trello stories?
#184752101

2023-04-22 08:28 UTC, bergad37 requested changes
Rebase your branch with the `develop` branch. There are some conflicts!

2023-04-24 10:28 UTC, nishimweprince approved these changes
Excellent work!!

2023-04-24 10:45 UTC, bergad37 approved these changes

2023-04-24 11:06 UTC, irakevine approved these changes
You did a great job!! keep it up..

2023-04-24 11:11 UTC, Dyves1 approved these changes

2023-04-24 12:15 UTC, niyontwali approved these changes

2023-04-24 12:15 UTC, merged